# Stage 1: Build
FROM maven:3.8.5-openjdk-17 AS build
COPY . /app
RUN mvn -f /app/pom.xml clean package -DskipTests

# Stage 2: Run
FROM openjdk:17-jdk-slim
COPY --from=build /app/target/*.jar app.jar
# 建立資料存放區
RUN mkdir /data
ENTRYPOINT ["java", "-jar", "/app.jar"]